name: bespoke_app
description: BW Government Payment app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  nfc_manager: ^3.2.0
  feature_folder_cli: ^0.1.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  shared_preferences: ^2.0.18
  rxdart: ^0.27.7
  jwt_decoder: ^2.0.1
  http: ^0.13.5
  dotted_line: ^3.1.0
  provider: ^6.0.5
  flutter_screenutil: ^5.6.0
  google_fonts: ^4.0.3
  flutter_masked_text2: ^0.9.1
  mobile_scanner: ^2.1.0
  custom_sliding_segmented_control: ^1.7.4
  qr_flutter: ^4.0.0
  email_validator: ^2.1.17
  device_info_plus: ^9.0.2
  json_annotation: ^4.8.0
  checkmark: ^0.0.2+1
  currency_text_input_formatter: ^2.1.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
